# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01a04dd1d041c718dcf5c4d696a868785bf201b34f4b968ebf6153aa344599385bb4de20ba5f360c8502af723ee98bf65541a33fc08b9f60dd4e1192fa791ab2

test:
  secret_key_base: 2b1c91fd751c553642a5dbca556438a428eba7c4b9312a404c2a285fc5078fac2a0808ed595adab1259179f50245e6219fcc353e980ec0260a25067ddf3d3b69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
